import Header from './components/header';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ES REPORT',
  description: 'Generated by create ES app',
  icon:'https://esreport.vercel.app/es1.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
      <meta property="apple-touch-icon" content="https://esreport.vercel.app/es1.png" />
      </head>
      <body className={inter.className}>
        <Header/>
        <main >
          {children}
        </main>
      </body>
    </html>
  )
}
