import Favicon from '../public/favicon.ico'
import Header from './components/header';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ES REPORT',
  description: 'Generated by create ES app',
  // icon:'https://esreport.vercel.app/es1.png',
  icons:[{rel:'icon',url:Favicon.src}],
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      {/* <head>
        <meta property="apple-touch-icon" content={metadata.icon} />
      </head> */}
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-YT5KDQJBP8"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
      
        gtag('config', 'G-YT5KDQJBP8');
      </script>
      <body className={inter.className}>
        <Header/>
        <main >
          {children}
        </main>
      </body>
    </html>
  )
}
